[package]
name = "fastqx"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "fastqx"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
futures = "0"
log = "0"
pyo3 = { version = "0", features = ["extension-module"] }
pyo3-asyncio = { version = "0", features = ["attributes", "tokio-runtime"] }
pyo3-log = "0"
sqlx = { version = "0", features = [
    "runtime-tokio",
    "postgres",
    "mysql",
    "sqlite",
] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
