# @file:	fastqx.pyi
# @author:	Jacob Xie
# @date:	2023/09/09 14:59:01 Saturday
# @brief:

from typing import List, Optional, Any
from dataclasses import dataclass

@dataclass
class FqxData:
    columns: List[str]
    types: List[str]
    data: List[List[Any]]

    def type_coercion(self) -> None: ...
    def to_json(self) -> Optional[str]: ...
    def to_json_pretty(self) -> Optional[str]: ...
    @classmethod
    def from_csv(cls, path: str, type_hints: List[str]) -> FqxData: ...
    def to_csv(self, path: str) -> None: ...

def new_fqx_data(columns: List[str], data: List[List[Any]]) -> FqxData: ...
def fqx_data_from_csv(path: str, type_hints: List[str]) -> FqxData: ...
def fqx_data_to_csv(data: FqxData, path: str) -> None: ...

class FqxConnector(object):
    def __init__(self, conn_str: str) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_close(self) -> bool: ...
    async def async_execute(self, sql: str) -> None: ...
    async def async_fetch(self, sql: str) -> FqxData: ...
    def execute(self, sql: str) -> None: ...
    def fetch(self, sql: str) -> FqxData: ...
    def save(self, data: FqxData, table_name: str, mode: str) -> None: ...
    def uncheck_save(self, data: FqxData, table_name: str, mode: str) -> None: ...
